dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=mhost
    - secure: PqNMjH4WxLHuo5XZRF4EKgM7cYGQXfwMKaHnf5uwrCYT1ZH2Lgaz/BP3wxuXdHqGWux8QzhF4lL9gwq9JmuaSljtAMtl3YNcCFgXvrzXjGzrIX4Yk6Xc+lZ8AVyUPik0FBcaUFvdDEhA+bFGCFv3O2VpjS+uSkdTjwiKDTKMqec6ijRs5cS873KGZDVBuyaLUYXqgEoRSEcAtd11QV53FOuNVlkPX4iOQkVJtOIk5hGvdzr9BujJ1SWXWd70AUqWxZkHG8Tg2l18AJXOjeECJZL8bNHXBP3ITC2MsYAoQuvHwn48qMbs4zZu27QP6PJx0s2Ns6Zj2f1v+tX67qcF0/XULhn8cNVXW2m5JA7jW24UH2vZSudSrGCIX4QfTIkleZ6lvygaWCj/CbxpTosg+01qhdcEHPYQw06Ge4b0vNA62ngqeJC15i6sMCM2OrzpmLBmjakQXkQ2NVWLZ3b0Av66OTZlUnpCWNgWI1ywi2lB09EeFQRDL7aNBF3Q+qa68zx+/Lleid4uqCM5C8I1HpqxHwsBYam5lYrae4+UytPc3kX+NbOLRHorXA81CVPLhRzFnsMYDtqaT/dmrQx3YK8A+3ND39he/rR5h4y39rfBle0OVNnyjNA1vl5xu+GtnPPWPHN/e4gR0uTEjXY6GpyEv9xpDseA9iKO56h1bUc=

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu DEPLOY_ARCH=amd64
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

    # macOS
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx

    # Rapsi
    - env: TARGET=armv7-unknown-linux-gnueabihf DEPLOY_ARCH=armhf
      rust: nightly

    # Testing for future releases of Rust
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

  allow_failures:
    - rust: beta
    - rust: nightly

branches:
  only:
    - master
    - travis-ci
    - "/^v.*$/"

before_install: set -e

install:
  - sh .ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash .ci/script.sh

after_script: set +e

before_deploy:
  - sh .ci/before_deploy.sh

deploy:
  - provider: packagecloud
    username: lukaspustina
    token:
      secure: SM2/BZdkaGv3X0jmojaDE9ovM7+Wd9Macsral+Z/1eX8pBfONtiDcauUZW0yRuJPCgBYRXErSYx/Hci9W4O8EvvjVdJNaEupegZlJwnqllGnhvLmEWYL5mDigPmXQVUmO38DfQiONFIiMb48Bt/EYHcf95ObSCqEIVVAFblTTZNzbmrFPzafFLMqr3qquPixPGIDXSeJbgC5WeS4ECkH+YZLhN3HmKSOPfQJRzGkHnIKZwuXqm11NCfSLrekPogg9XLhAAvnDyfX0myarPFqmDJhtuTK6IqZEnGyQBvg/jOnRsAPMzCMcnXR27ZWNBzyQv2Vb8WdchdMfEb/6qN/spuDmu68MtsIk9rXz2WDgHS8MMHk9RRrGzazY4rWPFQGkeTNJ3P1a6HTi4P+oXIHLQJQ1C/IuocPrtFkyGQwWl9ySpOOwwt4idSVVaq3wOQsrHNGhJykicQI20Gj059Sfud4B0SWgoEWp7gGhne0w4LJIF7mvt+0sKm3nZFIvZtWLdckh6m1jDT2lGmv3jPVgfdudczSsoAt35ktsvClCezoe2PbUYBNXPBA8QFzNYnL6yEAEtN/4L5pb5m5SwfD9VRLRNx5qZ11p5mFb8mJwUjFUP+xW/BpSztsMwN+KhYItY2G15k61HQJjkMY0p4U9w/T0GgOQItA/D1L2LCf2HM=
    repository: opensource
    dist: ubuntu/trusty
    package_glob: "**/*.deb"
    skip_cleanup: true
    on:
      tags: true
      condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$DEPLOY_ARCH"
  - provider: releases
    api_key:
      secure: drj6ONedluZto8vwLy1KaXHeFwqRPfAqKvwSg1WoVDcWMzt6Fv1GERIMbNx2h/nvDkGRhVV0AVN9Kax6tv9hSrY6F9jaRs3+2GRRfCMoIhSLsq/1vyvL3F040IkSPIhTsEkaeapJTdU8jS3PkAFguGhQkycssfOnDxTGY6/SBw8QNRuin0enZoxASH7gVqZxLk1FjOg2PC+GliZm8my9hJOVVjmE24+Dp3NUKtJFKvr+K9YwYUqh243G8dWXAN7AopwbiZCNkazFeCMdlCdPDfR4gmQl7g58/qAQO5BaOiaUICBdFALRQ3kti4c42e7UbVfA7gpVa6X1hiMUtt91nImGkvsVftqavnFiREMhDVU6nycT7Afo6SCLWASQE/ZUKKJI8aRNVstTzoiaRh+m4tfLqUzkeuG6jWsz202zioUpAAK/ya1lCLzrjDoyp/6Y87HLaKQh7Gbwr7l6he4n3ND1wOfFKl76XnXBS2d6sin1P6mvtC0j8PRoaZAgnJii6i7GXmYYHX/Z9LfIqOVKeXUKj7nvcNSl94XLQwbewnhBqIWLXZS4aB8W0Jx8qtVXonBmHdVtlul62/NTr746SgWVwBzBraKwxDT9LCyiqk55m4D07MMnoCZ/D7EkoT4htQHLrGF1sYnsb4FReDGj0z5W/i+9r5p+IisNQzDWglc=
    file_glob: true
    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    skip_cleanup: true
    on:
      tags: true
      condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$DEPLOY_ARCH"
  - provider: script
    script: .ci/cargo_publish.sh ${CRATES_IO_TOKEN}
    on:
      tags: true
      condition:
      - "$TRAVIS_OS_NAME == linux"
      - "$DEPLOY_ARCH == amd64"

