[package]
name = "service_world"
version = "0.0.1"
authors = ["Lukas Pustina <lukas@pustina.net>"]
description = "Discover services from Hasicorp's consul"
repository = "https://github.com/lukaspustina/service_world.git"
documentation = "https://github.com/lukaspustina/service_world.git"
readme = "README.md"
license = "MIT"
keywords = ["network", "consul", "service", "discovery"]
include = [
  "README.md",
  "LICENSE",
  "**/*.rs",
  "Cargo.toml",
]

[badges]
travis-ci = { repository = "lukaspustina/service_world", branch = "master" }
appveyor = { repository = "lukaspustina/service_world", branch = "master" }

[[bin]]
name = "sw-discover"
path = "src/bin/sw-discover.rs"

[dependencies]
clap = "2"
consul = "^0.2"
tabwriter = "^1.0"

