[package]
name = "service_world"
version = "0.0.0"
authors = ["Lukas Pustina <lukas@pustina.net>"]

[[bin]]
name = "sw_inspect"
path = "src/bin/sw_inspect.rs"
doc = false

[dependencies]
consul = "^0.2"
tabwriter = "^1.0"

